### ISSUE TITLE
transfer to moneta-org?

### ISSUE THREAD

**Issue by minad** [moneta-rb/moneta#161]
@asppsa It would be great if we could transfer the gem to a moneta-org since the travis builds are hogging my pipeline ;) What do you think?

**Comment by asppsa** [comment]
Yes, this sounds great.  Do you want me to create the org?  I see that [moneta](https://github.com/moneta) is taken already, so perhaps something like moneta-rb?

**Comment by asppsa** [comment]
Docs are here: https://help.github.com/en/articles/transferring-a-repository

**Comment by minad** [comment]
Yes, you can create that with us as admins and I will transfer the repo. moneta-rb sounds good!
