### ISSUE TITLE
using Pool in combination with Memcached leads to RingErrors

### ISSUE THREAD

**Issue by TheWudu** [moneta-rb/moneta#173]
When using Pool together with MemcachedDalli, a Dalli::RingError is raised nearly immediately after the code runs multithreaded. The issue is:

https://github.com/moneta-rb/moneta/blob/master/lib/moneta/adapters/memcached/dalli.rb#L23

The options are mutated by removing the server, but then passed into the next pool "member" again, which then defaults to 127.0.0.1.

So the first connection is correct, all the others not. 

So either dup there, or just do not remove the :server option. 

Best regards,
TheWudu

PS: MemcachedNative seem to have the same issue: 
https://github.com/moneta-rb/moneta/blob/master/lib/moneta/adapters/memcached/native.rb#L21

**Comment by asppsa** [comment]
Thanks for the report - your diagnosis seems spot on. Will attempt to resolve ASAP.

**Comment by asppsa** [comment]
@TheWudu, would you be able to try out the `builder-options-dup` branch and see if it resolves the issues you are seeing?  It's passing tests now, but would be good to get confirmation from you.

**Comment by asppsa** [comment]
@TheWudu, feel free to reopen this issue if the problem isn't fixed.

**Comment by TheWudu** [comment]
Sorry for the late response. It seem to work properly, when will you release a new version of the gem?

**Comment by asppsa** [comment]
I'll try to do so this week some time.

**Comment by asppsa** [comment]
@TheWudu I've made a 1.3.0 release now, which has the fix for your issue.  Hope that works.
