### ISSUE TITLE
Setting the database using `:db` option does not work for Mongo adapter

### ISSUE THREAD

**Issue by eflukx** [moneta-rb/moneta#194]
Initializing Moneta with the Mongo adapter like below, causes it to use the `admin` database, the `:db` option is seemingly ignored:
    
    store = Moneta.new(:Mongo, db: 'moneta')

_This_ works though: here `:database` is passed as a generic option to `Mongo::Client`

     store = Moneta.new(:Mongo, database: 'moneta')

Setting te database afterwards also does not work e.g. 

    store.adapter.backend.use 'moneta'

Is seems the `Mongo::Client#use` method does not work as expected (might be a bug, might be intentional?).  IMO the solution would be deprecating the `:db` option and document using the `:database` option. Having the `:db` option working as fallback, while throwing a deprecation warning.

**Comment by asppsa** [comment]
Thanks for this - I'll take a look over the weekend.

**Comment by asppsa** [comment]
@eflukx sorry, I forgot to say - I've merged a fix for this issue and added some extra tests.  If you're able to verify that the latest `master` fixes your issue, that would be super.  I'll do a release ASAP.
