### ISSUE TITLE
missing tag for 1.4.2

### ISSUE THREAD

**Issue by mtjhax** [moneta-rb/moneta#216]
I noticed that there is no tag for version 1.4.2, so the link to the source code from rubygems.org 404s: https://github.com/moneta-rb/moneta/tree/v1.4.2

**Comment by asppsa** [comment]
Thanks for finding this, and apologies for the oversight.  I've added the tag now and also made a GitHub release: https://github.com/moneta-rb/moneta/releases/tag/v1.4.2
