### ISSUE TITLE
Null Adapter missing config method

### ISSUE THREAD

**Issue by basex** [moneta-rb/moneta#223]
Since moneta 1.5 when using the Null adapter I get the following error:

```shell
NoMethodError: undefined method `config' for #<Moneta::Adapters::Null:0x00007f16d355ebc8>
        adapter_config = adapter&.config
                                ^^^^^^^^
gems/moneta-1.5.1/lib/moneta/proxy.rb:148:in `config'
```

Seems to be related with this change:
* Adapters - internally, most (all?) adapters now inherit from a base Adapter class

**Comment by asppsa** [comment]
Thanks for the report - I think you are right that this will be to do with the switch to the config DSL.  A minimal repro is:

```rb
store = Moneta.new(:Null, expires: 1)
store['x'] = 1 # raises the error
```

I'll make a fix ASAP

**Comment by basex** [comment]
@asppsa Thanks a lot. I tested locally the fix and it's working.
