### ISSUE TITLE
the LMDB links are incorrect:

### ISSUE THREAD

**Issue by libweirdness** [moneta-rb/moneta#224]
https://git.openldap.org/openldap/openldap/tree/mdb.master
is the master site, &

https://github.com/LMDB/lmdb
is the fully-browsable read-only mirror.

with
https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/intro.doc
being the introduction to the thing.

hth, & Kaizen, eh?

( :

**Comment by asppsa** [comment]
Thanks for the pointers - I'll update
