### ISSUE TITLE
File adapter needs to open file with 'rb'

### ISSUE THREAD

**Issue by pbennettinin** [moneta-rb/moneta#74]
Using the :HashFile adapter and storing a pretty simple hash value as the key, Moneta will save a value it is incapable of loading.  The save adapter writes the marshaled value as:
        ::File.open(temp_file, 'wb') {|f| f.write(value) }
yet the load code simply calls:
        ::File.read(store_path(key)
The file is not loaded in binary mode and the marshaler raises the 'marshal data too short' exception.
The code should be:
        ::File.read(store_path(key), {mode: 'rb'})

**Comment by avdi** [comment]
Hiya! Do you have any plans to push this out to a new gem version?

**Comment by asppsa** [comment]
There's an open issue for this -- see #87.  Basically this gem had widespread test failures that would have made releasing a bad idea.  They are almost all resolved now, but there are still a couple of 1.9.3 issues, according to Travis.

**Comment by avdi** [comment]
Gotcha. In case I can help: is it just the failing tests in runs 488.37 and 488.43 that are holding up the release?

**Comment by asppsa** [comment]
@avdi, yes those are the two that we would want green, but just a warning that I think some of the failures may be intermittent.  When I last tried to get all the tests green it felt a bit like whac-a-mole.  Any help you can provide will be very much appreciated though!

@minad, are you happy for a new release to go ahead if we can get all outstanding tests to pass?

**Comment by pbennett** [comment]
It looks like the failures were because the build server couldn't connect to remote repos.

**Comment by asppsa** [comment]
I'm going to go ahead and say that yes, if we can fix those 1.9.3 travis problems, we'll be good to put out a new release of moneta.  Sorry for the delay.
