### ISSUE TITLE
Cassandra-Driver adapter

### ISSUE THREAD

**Issue by Poil** [moneta-rb/moneta#81]
Hi

Moneta seem to use the old ruby gem "cassandra" which are no more supported; any plan to migrate to cassandra-driver ?

Best regards

**Comment by minad** [comment]
Yes sure. Would you like to do create a pull request?

**Comment by rezpe** [comment]
Hey,

   I have implemented a first adapter for the new cassandra driver: (gem 'cassandra-driver') from Datastax. However, there are BIG differences in the access to the values as the new driver is using the CQL language (similar to SQL). I would like to discuss in here if you agree with my choices and then it would be great if we can integrate the changes in the official code.

In the old version in order to retrieve values, the adapter received a key in the form of a string and it returned a string with the value. You could use moneta transformers to process the key or the value. In the new version, I propose we send the key as a String as well but as a list of conditions for the CQL query. 

I have put a first preliminary version below of moneta/adapters/cassandra that ONLY reads. If this direction is good, then I'll add the code to write values:

```ruby
require 'cassandra'

module Moneta
  module Adapters
    # Cassandra backend
    # @api public
    # @author Sebastien Perez
    class Cassandra
      include Defaults
      attr_reader :backend

      # @param [Hash] options
      # @option options [String] :keyspace ('moneta') Cassandra keyspace
      # @option options [String] :table ('moneta') Cassandra column family
      # @option options [String] :host ('127.0.0.1') Server host name
      # @option options [Integer] :port (9160) Server port
      # @option options [::Cassandra] :backend Use existing backend instance
      def initialize(options = {})
        cluster = ::Cassandra.cluster(hosts:options[:host])
        @backend  = cluster.connect(options[:keyspace])
      end

      # (see Proxy#load)
      # The key would have a format like this one
      # key = ' market = "US" AND machine="seb_machine" '
      # where market and machine are columns used to partition the Cassandra Table 
      def load(key, options = {})
        table = options[:table]
        puts "SELECT * FROM #{table} WHERE #{key} LIMIT 1"
        result = @backend.execute("SELECT * FROM #{table} WHERE #{conditions} LIMIT 1")
        value = nil
        if result.first
          value = result.first["value"]
        else
          nil
        end
      end

      # (see Proxy#close)
      def close
        @backend.disconnect!
        nil
      end
    end
  end
end

```

**Comment by minad** [comment]
Sure I will accept such a pr, please ensure that the test case for the cassandra driver works!

**Comment by rezpe** [comment]
Sorry for my ignorance, please can you tell me how to execute the tests for the Cassandra Adapter ?

**Comment by minad** [comment]
rspec spec/*

But be aware that the specs are generated using script/generate-specs for each adapter

**Comment by rezpe** [comment]
Don't you think this should be an entireliy new adapter since the philosophy is quite different. I do not think my adapter will pass the specs of the current one. Let me know your thoughts. I would call it CassandraCQL3 adapter.

**Comment by minad** [comment]
Well, you have to make it conform to the specs as good as possible :) I don't want to have to different cassandra adapters.

**Comment by minad** [comment]
Except both of the backends are maintained, then it makes sense to provide two different adapters.

**Comment by rezpe** [comment]
Thing is the old backend is being discontinued by the Cassandra team. Only
CQL3 will be supported ...

**Comment by minad** [comment]
Ok. then yours will be the only one :)

**Comment by rezpe** [comment]
The driver is ready (expires option are not supported, but everything else seems fine). I have executed rspec but I have the following error:

'''
helper.rb:52:in `block in <top (required)>': undefined method `color_enabled=' for #<RSpec::Core::Configuration:0x00000001361838> (NoMethodError)
'''

**Comment by rezpe** [comment]
Also, this error occurs on the master branch WITHOUT my changes. Have you seen something similar ?

**Comment by minad** [comment]
maybe you can update the rspec dependencies? It should be pretty easy to debug.
