### ISSUE TITLE
Allow customisation of column lengths when using SQL adapters

### ISSUE THREAD

**Issue by ikapelyukhin** [moneta-rb/moneta#86]
Hello,

I've added Moneta gem to my project that uses MySQL database with ActiveRecord adapter to be used as session storage. The database default encoding is utf8mb4. On the first run after the gem has been added it creates a new `moneta` table, but adding an index to it fails:

> active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query': Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_moneta_on_k`  ON `moneta` (`k`)  (ActiveRecord::StatementInvalid)

I can restart the server and it works fine next time, but the table is missing an index on `k` column.

So I guess VARCHAR(255) for key column doesn't always work on MySQL. :-)

**Comment by somerandomlogin** [comment]
I've simply recreated `moneta` table and it's index with utf8 encoding, I guess there is no way 4-byte utf8 characters can end up in key values.

**Comment by asppsa** [comment]
In case anyone is interested, there's a good explanation of this issue here: https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by ikapelyukhin** [comment]
The reason for the issue is clear. The default 255 column length doesn't work with `utf8mb4` though (maybe should be documented, maybe should be handled automatically during the table creation).

**Comment by asppsa** [comment]
I think "doesn't work" is not quite right.  As per the link above, for MySQL 5.7 and above, this should work without any change, as the default index key prefix length has been increased.  For MySQL 5.5 and 5.6, you can enable the [`innodb_large_prefix`](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix) option.

I take your point though that if someone wanted to use utf8mb4 without the above won't work.  It would probably be ideal if moneta's various SQL adapters offered greater customization for situations such as this.

**Comment by asppsa** [comment]
The ActiveRecord adapter in master now supports passing a `:create_table` option.  You can use this to pass in a Proc which will create the table if it doesn't exist.  e.g.,

~~~ ruby
store = Moneta::Adapters::ActiveRecord.new(
  table: :moneta,
  create_table: lambda do |conn|
    conn.create_table(:moneta, id: false) do |t|
      t.string :k, null: false, limit: 128
      t.binary :v
    end
    conn.add_index(:moneta, :k, unique: true)
  end)
~~~

Will try to add something similar to the other SQL adapters ...

**Comment by asppsa** [comment]
Sequel adapter now has an equivalent `:create_table` option too.  Note I've updated the above example to include a `table_exists?` check.  Also, both adapters also accept `create_table: false` to prevent the default table creation routine from running.

**Comment by ikapelyukhin** [comment]
Noice :+1:
